"""empty message

Revision ID: 01abb9ffe32f
Revises: f4b5fca5147d
Create Date: 2018-09-28 21:50:06.647335

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01abb9ffe32f'
down_revision = 'f4b5fca5147d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('review', sa.Column('title', sa.Text(), nullable=True))
    op.add_column('user', sa.Column('tripadvisor_uid', sa.String(length=100), nullable=True))
    op.create_index(op.f('ix_user_tripadvisor_uid'), 'user', ['tripadvisor_uid'], unique=True)
    op.drop_index('ix_user_tripadvisor_username', table_name='user')
    op.drop_column('user', 'tripadvisor_username')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('tripadvisor_username', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.create_index('ix_user_tripadvisor_username', 'user', ['tripadvisor_username'], unique=True)
    op.drop_index(op.f('ix_user_tripadvisor_uid'), table_name='user')
    op.drop_column('user', 'tripadvisor_uid')
    op.drop_column('review', 'title')
    # ### end Alembic commands ###
