"""empty message

Revision ID: 09f640e02054
Revises: 3496f7833d74
Create Date: 2018-09-26 22:58:07.357481

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09f640e02054'
down_revision = '3496f7833d74'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_place_name'), 'place', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_place_name'), table_name='place')
    # ### end Alembic commands ###
