"""empty message

Revision ID: 3496f7833d74
Revises: a2a801e0bcdd
Create Date: 2018-09-26 16:43:36.106403

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3496f7833d74'
down_revision = 'a2a801e0bcdd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('place', 'image_url')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('place', sa.Column('image_url', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
