"""empty message

Revision ID: 820415fbf067
Revises: 112f185fd625
Create Date: 2018-09-26 15:57:32.641645

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '820415fbf067'
down_revision = '112f185fd625'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('place', sa.Column('tripadvisor_id', sa.Integer(), nullable=True))
    op.drop_column('place', 'ta_id')
    op.add_column('user', sa.Column('tripadvisor_username', sa.String(length=100), nullable=True))
    op.create_index(op.f('ix_user_tripadvisor_username'), 'user', ['tripadvisor_username'], unique=False)
    op.drop_index('ix_user_password', table_name='user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_user_password', 'user', ['password'], unique=False)
    op.drop_index(op.f('ix_user_tripadvisor_username'), table_name='user')
    op.drop_column('user', 'tripadvisor_username')
    op.add_column('place', sa.Column('ta_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('place', 'tripadvisor_id')
    # ### end Alembic commands ###
