"""empty message

Revision ID: 8d9024bc47cf
Revises: b6e19a00d39f
Create Date: 2018-09-30 16:11:05.912006

"""
from alembic import op
import sqlalchemy as sa
from geoalchemy2.types import Geography


# revision identifiers, used by Alembic.
revision = '8d9024bc47cf'
down_revision = 'b6e19a00d39f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('place', sa.Column('location', Geography('POINT'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('place', 'location')
    # ### end Alembic commands ###
