"""empty message

Revision ID: a2a801e0bcdd
Revises: baf6cddec253
Create Date: 2018-09-26 16:41:59.007262

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2a801e0bcdd'
down_revision = 'baf6cddec253'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('place', sa.Column('navicontainer', sa.String(length=18), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('place', 'navicontainer')
    # ### end Alembic commands ###
