"""empty message

Revision ID: aa3aa102fce0
Revises: fef5478c076e
Create Date: 2018-09-27 20:10:27.770841

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa3aa102fce0'
down_revision = 'fef5478c076e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_email', table_name='user')
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.drop_index('ix_user_tripadvisor_username', table_name='user')
    op.create_index(op.f('ix_user_tripadvisor_username'), 'user', ['tripadvisor_username'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_tripadvisor_username'), table_name='user')
    op.create_index('ix_user_tripadvisor_username', 'user', ['tripadvisor_username'], unique=False)
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.create_index('ix_user_email', 'user', ['email'], unique=False)
    # ### end Alembic commands ###
