"""empty message

Revision ID: b6e19a00d39f
Revises: 01abb9ffe32f
Create Date: 2018-09-28 22:30:54.434022

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6e19a00d39f'
down_revision = '01abb9ffe32f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('place', sa.Column('image_url', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('place', 'image_url')
    # ### end Alembic commands ###
