"""empty message

Revision ID: baf6cddec253
Revises: 820415fbf067
Create Date: 2018-09-26 16:12:06.162576

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'baf6cddec253'
down_revision = '820415fbf067'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('place', sa.Column('image_url', sa.String(length=200), nullable=True))
    op.add_column('place', sa.Column('rating', sa.SmallInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('place', 'rating')
    op.drop_column('place', 'image_url')
    # ### end Alembic commands ###
