"""empty message

Revision ID: f4b5fca5147d
Revises: aa3aa102fce0
Create Date: 2018-09-28 20:08:18.233922

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4b5fca5147d'
down_revision = 'aa3aa102fce0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('place', sa.Column('tripadvisor_url', sa.Text(), nullable=True))
    op.drop_column('place', 'tripadvisor_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('place', sa.Column('tripadvisor_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('place', 'tripadvisor_url')
    # ### end Alembic commands ###
