"""empty message

Revision ID: fef5478c076e
Revises: 09f640e02054
Create Date: 2018-09-26 23:04:52.392215

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fef5478c076e'
down_revision = '09f640e02054'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('place',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('place_type', sa.SmallInteger(), nullable=True),
    sa.Column('tripadvisor_id', sa.Integer(), nullable=True),
    sa.Column('navicontainer', sa.String(length=18), nullable=True),
    sa.Column('naviaddress', sa.String(length=18), nullable=True),
    sa.Column('rating', sa.SmallInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_place_name'), 'place', ['name'], unique=False)
    op.create_foreign_key(None, 'review', 'place', ['place_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'review', type_='foreignkey')
    op.drop_index(op.f('ix_place_name'), table_name='place')
    op.drop_table('place')
    # ### end Alembic commands ###
